parameters:
- name: OOBBranch
  displayName: Branch for OOB pipeline
  type: string
  default: 'none'
jobs:
- job: Release
  timeoutInMinutes: 180
  pool:
    name: $(AgentPool)
    demands: npm
  variables:
    LocalRepoName: 'LocalRepo'
  steps:
  - task: PowerShell@2
    displayName: checkout OOBbranch
    inputs:
      targetType: 'inline'
      script: |
          if ('${{ parameters.OOBBranch }}' -ne 'none') {
            git remote set-url origin https://azure-powershell-bot:$Token@github.com/Azure/azure-powershell.git;
            git fetch origin
            git checkout -b ${{ parameters.OOBBranch }} origin/${{ parameters.OOBBranch }}
          }
  - pwsh: |
      $buildNumber = git rev-list --parents HEAD --count --full-history
      write-host $buildNumber
    displayName: 'Build Installer'